### PR TITLE
add formatting to travis commands

### PR DESCRIPTION
**Pull request by cs01**
I took a shot at making a `CONTRIBUTING` page, and I also ran `gofmt -l -e -s`, which modified some of the files.

### CODE REVIEW

**Comment by aleb** [comment]
Merged, except the change to the README file because I `export GOPATH=/tmp/x` and ran go install and it did not work. I see "get" also installs:
```
$ go help get
...
Get downloads the packages named by the import paths, along with their
dependencies. It then installs the named packages, like 'go install'.
```

Thanks!

**Comment by cs01** [comment]
I see my commit in the master branch, but this PR says `This pull request is closed, but the zeeaero:cs01/travis-formatting branch has unmerged commits.`

Why is this?

**Comment by aleb** [comment]
I amended the commit to revert the README change and pushed manually to origin/master - the commit is different. 
In gitk you can see for example this to figure out a commit has been changed:
```
Author: Chad Smith <cs01@users.noreply.github.com>  2017-07-12 22:04:59
Committer: Alexandru Băluț <alexandru.balut@gmail.com>  2017-07-12 23:20:08
```
On github this appears as "cs01 committed with aleb 2 hours ago" if you look at Code > commits.

**Comment by cs01** [comment]
fwiw amending/force pushing over someone else's commit is something we avoid so we can get a clear picture of the sequence of commits and who made them. To me this PR is now a little more confusing since it looks like my changes weren't merged. IMO it would be more clear if this were merged and then changed after the fact, or maybe this is a common workflow in github that I'm just not accustomed to.

**Comment by aleb** [comment]
We are more fond of the "Phabricator" philosophy which says the detailed history is not very important, but what's useful is being able to make sense out of that history.

This means we try to avoid having "merge" commits, and have instead a linear history. This is done with something like `git merge --squash branch_to_be_merged` when the branch is messy, and with `git rebase` when the branch is clean but not fast-forward. Would it be too much if, once a pull request is accepted, you do this and push yourself to daedaleanai/reqtraq? 

In this case the change was minor, that's why I did it myself so I can merge right away. Normally we don't amend others's commits. I realize the pull request might appear as "red" instead of "green", unfortunately the github philosophy is to merge everything as is, and is not compatible with ours. So not common to github at all.

I assume the association with the pull request (with comments and replies) might be lost, but the relevant info should be in the commit message, code, code comments, docs. A pull request is just a github specific mechanism, I don't think it's worth to keep track of pull requests.

What do you think?

**Comment by cs01** [comment]
>  detailed history is not very important, but what's useful is being able to make sense out of that history

totally agree. Have you tried the options github provides when merging? There is the standard merge, but there is also options to squash and to rebase:

image

Using the button ensures continuity between code, comments, and merged code.

> A pull request is just a github specific mechanism, I don't think it's worth to keep track of pull requests.

Pull requests have more utility than just doing these code reviews; they are also automatically referenced in Github Issues if the issue number is referenced in a commit or PR comment. This enables users to look at an issue and immediately see all the comments in the issue, as well as all the associated pull requests and comments therein. It helps create a wholistic picture of all discussion around a certain issue and bi-directional links between issues and PRs. Overall I agree, the majority of the important information is contained in code, docs, etc., but sometimes understanding what changes were made, why, and what debate ensued can be useful too.

**Comment by aleb** [comment]
Never noticed the different Github merge options, thanks!

**Pull request closed without merging**
