### PR TITLE
SWL<->Code matrix

### PR DESCRIPTION
**Pull request by aleb**

### CODE REVIEW

**Comment by aleb** [comment]
Fixed the bottom-up report. Please have a look.

**Comment by leckardt** [comment]
I can confirm bottom-up is working. 
I get an error when I try to access the CODE, LTC or HTC matrices.

Linking from requirement to code seems to be working well, did a few tests. 

As the code also relies on universal-ctags, could you add it to the dependencies as well, as well as a required version? The first one I tried did not work with this code.

**Comment by aleb** [comment]
The SWH-HTC and SWL-LTC matrices are not supported yet.
I mentioned the universal-ctags dependency. They made no release yet, so there are no versions.

**Comment by leckardt** [comment]
Okay :)
ready to merge

**Pull request merged**
